version: '3'

services:
  consul:
    image: consul:1.9.7
    container_name: consul
    ports:
      - "8500:8500"  # UI
      - "8600:8600/udp"  # DNS
      - "8400:8400"  # RPC
      - "8301:8301"  # Serf LAN
      - "8302:8302"  # Serf WAN
    command: "agent -dev -client=0.0.0.0"
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - challenge-1
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - challenge-1
    volumes:
      - ./.docker/zookeeper-data:/var/lib/zookeeper
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
       - "29092:29092"
    networks:
      - challenge-1
    volumes:
      - ./.docker/kafka-data:/var/lib/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
volumes:
  mongodb_data:
networks:
  challenge-1:
    driver: bridge