version: '3'

services:
  consul:
    image: consul:1.9.7
    container_name: consul
    ports:
      - "8500:8500"  # UI
      - "8600:8600/udp"  # DNS
      - "8400:8400"  # RPC
      - "8301:8301"  # Serf LAN
      - "8302:8302"  # Serf WAN
    command: "agent -dev -client=0.0.0.0"
    networks:
      - challenge-1

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - challenge-1

volumes:
  mongodb_data:

networks:
  challenge-1:
    driver: bridge
